spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      endpoint: ${AWS_SQS_ENDPOINT}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      sqs:
        queues:
          video-status: ${AWS_SQS_VIDEO_STATUS_QUEUE}
        listener:
          missing-queue-destination-behavior: ignore

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

management:
  endpoint:
    health:
      show-details: never

jwt:
  secret: ${JWT_SECRET}

