services:
  postgres:
    image: postgres:16-alpine
    container_name: fiapx-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  localstack:
    image: localstack/localstack:3.8.1
    container_name: fiapx-localstack
    environment:
      SERVICES: sqs
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/localstack/init:/etc/localstack/init/ready.d:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  sqs-admin:
    image: pacovk/sqs-admin
    container_name: fiapx-sqs-admin
    environment:
      - SQS_ENDPOINT_URL=http://localstack:4566
      - SQS_AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "3999:3999"
    depends_on:
      localstack:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: fiapx-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: fiapx-auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod,local
      - DB_URL=jdbc:postgresql://fiapx-postgres:5432/fiapx_auth
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  video-api-service:
    build:
      context: .
      dockerfile: video-api-service/Dockerfile
    container_name: fiapx-video-api-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod,local
      - DB_URL=jdbc:postgresql://fiapx-postgres:5432/fiapx_video
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SQS_VIDEO_STATUS_QUEUE=video-status-api-queue
      - UPLOAD_DIR=/app/storage/uploads
      - FRAMES_DIR=/app/storage/frames
      - ZIPS_DIR=/app/storage/zips
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      auth-service:
        condition: service_started
    volumes:
      - shared-storage:/app/storage

  video-worker-service:
    build:
      context: .
      dockerfile: video-worker-service/Dockerfile
    container_name: fiapx-video-worker-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod,local
      - DB_URL=jdbc:postgresql://fiapx-postgres:5432/fiapx_video_worker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_SQS_VIDEO_UPLOADED_QUEUE=video-uploaded-queue
      - AWS_SQS_VIDEO_STATUS_API_QUEUE=video-status-api-queue
      - AWS_SQS_VIDEO_STATUS_NOTIFICATION_QUEUE=video-status-notification-queue
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - UPLOAD_DIR=/app/storage/uploads
      - FRAMES_DIR=/app/storage/frames
      - ZIPS_DIR=/app/storage/zips
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - shared-storage:/app/storage

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: fiapx-notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod,local
      - DB_URL=jdbc:postgresql://fiapx-postgres:5432/fiapx_notification
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_SQS_VIDEO_STATUS_QUEUE=video-status-notification-queue
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
      mailhog:
        condition: service_healthy

volumes:
  postgres_data:
  localstack_data:
  shared-storage:
