server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: video-api-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    hibernate:
      ddl-auto: update

# Configurações de armazenamento da aplicação
app:
  sqs:
    queues:
      video-status: ${AWS_SQS_VIDEO_STATUS_QUEUE:video-status-api-queue}
  storage:
    upload-dir: ${UPLOAD_DIR:./storage/uploads}
    frames-dir: ${FRAMES_DIR:./storage/frames}
    zips-dir: ${ZIPS_DIR:./storage/zips}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
