spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      sqs:
        missing-queue-destination-behavior: ignore
      endpoint: ${AWS_SQS_ENDPOINT}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
jwt:
  secret: ${JWT_SECRET}

app:
  sqs:
    queues:
      video-status: ${AWS_SQS_VIDEO_STATUS_QUEUE:video-status-api-queue}
  storage:
    upload-dir: ${UPLOAD_DIR:/app/storage/uploads}
    frames-dir: ${FRAMES_DIR:/app/storage/frames}
    zips-dir: ${ZIPS_DIR:/app/storage/zips}

management:
  endpoint:
    health:
      show-details: never
