spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fiapx_video}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566 # Aponta diretamente para o LocalStack local
app:
  sqs:
    queues:
      video-status: ${AWS_SQS_VIDEO_STATUS_QUEUE:video-status-api-queue}

management:
  endpoint:
    health:
      show-details: always

jwt:
  # Secret fixo apenas para facilitá o desenvolvimento/testes locais no Postman
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
