server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: video-worker-service
  jpa:
    hibernate:
      ddl-auto: update

app:
  ffmpeg:
    binary-path: ${FFMPEG_BINARY_PATH:ffmpeg}
  storage:
    upload-dir: ${UPLOAD_DIR:./storage/uploads}
    frames-dir: ${FRAMES_DIR:./storage/frames}
    zips-dir: ${ZIPS_DIR:./storage/zips}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true