spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fiapx_video}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566 # Endpoint fixo do LocalStack
        queues:
          video-uploaded: video-uploaded-queue
management:
  endpoint:
    health:
      show-details: always
